### ISSUE TITLE
Want to update the CSS of the calendar.

### ISSUE THREAD

**Issue by SuperSonicHub1** [IonicaBizau/github-calendar#117]
I want to add CSS that better mimics GitHub's, specifically pertaining to the day squares of the calendar. I think it makes them pop a lot more, especially the empty ones.
![Display of new changes](https://user-images.githubusercontent.com/25624882/90346743-a5384300-dff9-11ea-9bb4-0c9571308c7f.png)

```css
.calendar-graph rect.day {
    shape-rendering: geometricPrecision;
    outline: 1px solid rgba(27, 31, 35, .04);
    outline-offset: -1px;
    rx: 2;
    ry: 2;
}
```
