### ISSUE TITLE
Provide customizable colors

### ISSUE THREAD

**Issue by Demfier** [IonicaBizau/github-calendar#48]
It would be really nice if we can also provide color customization where we can generate graphs of different shades.

**Comment by IonicaBizau** [comment]
Contributions are welcome! 🍀

**Comment by phi-line** [comment]
Any tips on where to start looking for colors?
I tried editing the hex codes found on this line `t.exports = ["#eee", "#d6e685", "#8cc665", "#44a340", "#1e6823"]` with no avail.

**Comment by IonicaBizau** [comment]
It's possible by overriding them directly in the CSS:

```css
/* level 1 (no commits) */
rect.day[fill="#ebedf0"] {
    fill: rgba(255, 0, 0, 0.1)
}

/* level 2 */
rect.day[fill="#c6e48b"] {
    fill: rgba(255, 0, 0, 0.3)
}
/* level 3 */
rect.day[fill="#7bc96f"] {
    fill: rgba(255, 0, 0, 0.5)
}
/* level 4 */
rect.day[fill="#239a3b"] {
    fill: rgba(255, 0, 0, 0.8)
}
/* level 5 */
rect.day[fill="#196127"] {
    fill: rgba(255, 0, 0, 1)
}
```
![image](https://user-images.githubusercontent.com/2864371/36196838-a3531f1a-117a-11e8-87b5-dbd31f1afe5b.png)
